spring:
  application:
    name: book-sb-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}}/${DB_NAME}
    username: ${DB_USERNAME}}
    password: ${DB_PASSWORD}}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata
server:
  port: 9090
  servlet:
    context-path: /book-manager